config/routes.rb
Gk40::Application.routes.draw do

  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'
  get 'users/update'

  resources :users
  resources :sessions, only: [:new, :create]
  resources :news
  get 'news/show'
  get 'news/create'
  get 'news/new'
  get 'news/edit'

  resources :monthly_readings, only: [:edit, :update]
  resources :ads, only: [:new, :create, :edit, :update, :show, :index]
  get 'documents/:id/download', to: 'documents#download', as: :document_download
  resources :documents
  resources :apartments, only: [:index]
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy' # , via: :delete

   root to: 'static_pages#home'

end

app/models/document.rb
# -*- encoding : utf-8 -*-
class Document < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :title, :doc
  has_attached_file :doc
	validates_attachment :doc,
		                    content_type: { content_type: ['image/gif', 'image/jpeg', 'image/pjpeg', 'image/png', 'image/tiff', 'application/msword', 'application/pdf'],
                    		                message: 'Только изображения и документы могут быть загружены (gif, jpeg, pjpeg, png, tiff, doc, pdf)' },
                    		size: { in: 0..10.megabytes, message: 'Размер файла слишком большой' }
end

app/controllers/documents_controller.rb
# -*- encoding : utf-8 -*-
class DocumentsController < ApplicationController
	def index
	check_sign_in
	@documents = Document.paginate(page: params[:page])
	end
	
	def download
		check_sign_in
		@docum = Document.find(params[:id])
	send_file(@docum.doc.path, disposition: 'attachment', type: @docum.doc_content_type)
	end
	
	def new
		check_admin
		@document = Document.new
	end

	def create
		return if !check_admin
		@document = Document.new(params[:document])
		if @document.save
			flash[:success] = 'Документ сохранено успешно!'
			redirect_to documents_path
		else
			flash.now[:error] = @document.errors.full_messages.to_sentence
			render 'new'
		end
	end
	def destroy
		return if !check_admin
		@doc = Document.find(params[:id])
		if @doc.destroy
			flash[:success] = 'Документ '+@doc.title+ 'удален.'
			redirect_to documents_path
		else
			flash[:error] = @document.errors.full_messages.to_sentence
			redirect_to documents_path
		end
	end
	private
	def check_sign_in
		return true if signed_in?
		redirect_to root_path
		return false
		
	end
	def check_admin
	    return true if (current_user && current_user.isAdmin?)
		redirect_to documents_path
		return false
	end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div>
<%if document != nil then%>
<%= link_to document.title, document_download_path(document)%>
<%= link_to( '<Удалить>', document_path(document),method: :delete, class: "del_link", confirm: "Подтвердите удаление документа \"#{document.title}\"") if current_user && current_user.isAdmin?%> 
<%else%>
<%= link_to "<Добавить документ>", new_document_path%>
<%end%>
</div>

app/views/documents/index.html.erb
<% provide(:title, 'Документы') %>
<h1>Документы</h1>

<%= will_paginate %>
<ul>
  <%= render(:partial => "document", locals: {document: nil}) if current_user && current_user.isAdmin?%> 
  <%= render :partial => "document", :collection => @documents %>  
</ul>
<%= will_paginate %>

app/views/documents/new.html.erb
<% provide(:title, 'Добавление документа') %>
<h1>Новый документ</h1>

<div class="row">
  <div>
    <%= form_for(@document) do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.label :title, 'Заголовок' %>
        <%= f.text_field :title %><br/>

        <%= f.label :doc,'Документ' %>
        <%= f.file_field :doc %><br/>

        <%= f.submit "Сохранить" %>
    <% end %>
  </div>
</div>