config/routes.rb
Gk40::Application.routes.draw do

  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'
  get 'users/update'

  resources :users
  resources :sessions, only: [:new, :create]
  resources :news
  get 'news/show'
  get 'news/create'
  get 'news/new'
  get 'news/edit'

  resources :monthly_readings, only: [:edit, :update]
  resources :ads, only: [:new, :create, :edit, :update, :show, :index]
  get 'documents/:id/download', to: 'documents#download', as: :document_download
  resources :documents
  resources :apartments, only: [:index]
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy' # , via: :delete

   root to: 'static_pages#home'

end

app/models/counter_type.rb
class CounterType < ActiveRecord::Base
  attr_accessible :name
  has_many :apartment_counters
  has_many :apartments, through: :apartment_counters
end

app/views/counters/_edit_meterage.erb
 <li>

	<%= f.fields_for meterage do |mf| %>
			<%= mf.label meterage.counter_type.name %>
			<%= mf.text_field :value %>
			<%= mf.text_field :value2 %>
		<% end %>
</li>

app/views/counters/_meterage.erb
<tr>
	<td>
		<%= meterage.counter_type.name %>
	</td>
	<td>
		<%=  if meterage.prev then if meterage.prev.value2==nil then "#{meterage.prev.value}" else "#{meterage.prev.value}/#{meterage.prev.value2}" end end%>
		
		</td>
	<td>
		<%= if meterage.value2==nil then "#{meterage.value}" else "#{meterage.value}/#{meterage.value2}" end %>
	</td>
</tr>

app/views/counters/_monthly_reading.erb

 <h4>
 <%= l monthly_reading.month, format: :meterage_date %>
 </h4>
 <table border="1"> 
	 <caption> <%= l monthly_reading.month, format: :meterage_date %> </caption>
	 <tr><td>Показатель</td><td>Начало периода</td><td>Конец периода</td></tr>
<%=render :partial => "counters/meterage", :collection => monthly_reading.meterages%>
</table>
<% if !monthly_reading.readonly? then%>
	<div><h4><%= link_to 'Ввести показания счетчиков', edit_monthly_reading_path(monthly_reading) %></h4></div>
<%end%>