config/routes.rb
Gk40::Application.routes.draw do

  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'
  get 'users/update'

  resources :users
  resources :sessions, only: [:new, :create]
  resources :news
  get 'news/show'
  get 'news/create'
  get 'news/new'
  get 'news/edit'

  resources :monthly_readings, only: [:edit, :update]
  resources :ads, only: [:new, :create, :edit, :update, :show, :index]
  get 'documents/:id/download', to: 'documents#download', as: :document_download
  resources :documents
  resources :apartments, only: [:index]
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy' # , via: :delete

   root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
<nav class="footer" align="right">
				<ul>
                    <li><%= link_to "О сайте",   about_path  %></li>
                    <li><%= link_to "Контакты", contact_path  %></li>
                    <li><%= link_to "Новости",  news_index_path %></li>
                </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header  align="center">
      	<%= link_to "ЖК 40", root_path, id: "logo" %>
         	<nav>
         		<ul>
         			<li><%= link_to "Домой",    root_path %></li>
                  <!--<li><%= link_to "Помощь",  help_path %></li>-->
                  
                   <% if signed_in? %>
				   <% if current_user.isAdmin? %>
                   	<li><%= link_to "Список квартир", apartments_path %></li>
                   	<li><%= link_to "Добавить новость", new_news_path %></li>
                   	<li><%= link_to "Добавить объявление", new_ad_path %></li>
					<% end %>
                   	<li><%= link_to "Профиль", current_user %></li>
                   	<!--<li><%= link_to "Настройки", '#' %></li>-->
                   	<li><%= link_to "Документы", documents_path %></li>
                   	<li><%= link_to "Выход", signout_path, method: "delete" %></li>
                   	</ul>
                   <% else %>
				    <li><%= link_to "Новости", news_index_path %></li>
					<li><%= link_to "Объявления", ads_path %></li>
                   	<li><%= link_to "Вход", signin_path %></li>
                   <% end %>                  
               </ul>
			   </nav>
			   <%= render 'shared/error_messages' %>
       </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all"%>
	<%= javascript_include_tag "application", media: "all" %>
	<%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
	
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= yield %>	  
	  <%= debug(params) if Rails.env.development? %>      
    </div>
	<%= render 'layouts/footer' %>
  </body>
</html>
</html>